In [1]:
word = ['1','2','3','4']

word[ : ] = [ ]

In [2]:
print(word)

[]


In [7]:
list1 = [1,2,2,3,4,5,5]
print(list1)

[1, 2, 2, 3, 4, 5, 5]


In [8]:
set1 = set(list1)
print(set1)

{1, 2, 3, 4, 5}


In [9]:
list2 = list(set1)
print(list2)

[1, 2, 3, 4, 5]


In [11]:
score = int(input("Enter your score "))

Enter your score 10


In [12]:
type(score)

int

In [14]:
paragraph = ["There was a fox." , 'It was brown in color.', "It was seen near that farm sometime back"]

In [15]:
# ['There', 'was', 'a', 'fox.', 'It', 'was', 'brown', 'in', 'color.', 'It', 'was', 'seen', 'near', 'that', 'farm', 'sometime', 'back']

In [17]:
single_word_list =[]

for sentence in paragraph:
    for word in sentence.split( ):
        single_word_list.append(word)

print(single_word_list)

['There', 'was', 'a', 'fox.', 'It', 'was', 'brown', 'in', 'color.', 'It', 'was', 'seen', 'near', 'that', 'farm', 'sometime', 'back']


In [ ]:
single_word_list  = [word for sentence in paragraph for word in sentence.split()]
print(single_word_list)

In [4]:
list1 = [1,2,3,4,0,0]
list2 = [5,6,7,8,9]
sum1 = list(map(lambda x,y : x+y,list1,list2))
print(sum1)

[6, 8, 10, 12, 9]


In [6]:
i = 2
j = i
print(id(i))
print(id(j))

140294301608272
140294301608272


In [11]:
for i in range(1,2):
    print(i)

1


In [14]:
import numpy as np

In [25]:
np_heights = np.array([71,74,76,72,72])

In [26]:
np_heights

array([71, 74, 76, 72, 72])

In [27]:
type(np_heights)

numpy.ndarray

In [28]:
np_heights * 2.54

array([180.34, 187.96, 193.04, 182.88, 182.88])

In [31]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = list1 + list2

In [32]:
list3

[1, 2, 3, 4, 5, 6]

In [29]:
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np3 = np1 + np2

In [30]:
np3

array([5, 7, 9])

In [35]:
nparray1 = np.array([1.0,2.25,3,4,True,False])
nparray1

array(['1.0', '2.25', '3', '4', 'True', 'False', 'True'], dtype='<U32')

In [42]:
ck = np.random.randint(3,10)

In [43]:
ck

4

In [44]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [45]:
np.zeroes()

AttributeError: module 'numpy' has no attribute 'zeroes'

In [5]:
import numpy as np
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
list = [1, 5 , 3, 7 , 4, 9]

In [55]:
a = np.array(list)

In [56]:
b = a.reshape(3,2)

In [57]:
b

array([[1, 5],
       [3, 7],
       [4, 9]])

In [63]:
np.reshape(b,(2,3))

array([[1, 5, 3],
       [7, 4, 9]])

In [33]:
a = [[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]]

array_1 = np.array(a)

In [34]:
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
print(array_1.reshape(5, 4)[array_1%2 != 0])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4

In [39]:
print(array_1[array_1%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [40]:
print(array_1[array_1%2 == 0].reshape(5, 2))

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [41]:
print(array_1[array_1%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
