In [3]:
import numpy as np

In [6]:
A = np.array([[2,7,1],[-2,1,8],[3,4,-2]])
B = np.array([[8,1,3],[3,5,8],[7,-2,-4]])

In [7]:
C = A @ B

In [8]:
C

array([[ 44,  35,  58],
       [ 43, -13, -30],
       [ 22,  27,  49]])

In [9]:
D = np.array([[2,1,1],[3,2,1],[2,1,2]])

In [10]:
E = np.linalg.inv(D)

In [11]:
E

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [1]:
########

In [16]:
B2 = np.array([[1,0],[0,1]])

In [17]:
B2

array([[1, 0],
       [0, 1]])

In [18]:
B2_inv = np.linalg.inv(B2)

In [19]:
B2_inv

array([[1., 0.],
       [0., 1.]])

In [20]:
B1 = np.array([[1,1],[2,-1]])

In [22]:
B1 @ B2_inv

array([[ 1.,  1.],
       [ 2., -1.]])

In [23]:
##########

In [24]:
v1 = np.array([[8],[6]])

In [25]:
v1

array([[8],
       [6]])

In [26]:
B1 = np.array([[1,0],[0,1]])

In [27]:
B2 = np.array([[2,-2],[1,1]])

In [28]:
B2_inv = np.linalg.inv(B2)

In [31]:
M = B2_inv @ B1 

In [32]:
M

array([[ 0.25,  0.5 ],
       [-0.25,  0.5 ]])

In [35]:
v2 = M @ v1

In [36]:
v2

array([[5.],
       [1.]])

In [37]:
#################

In [42]:
B2 = np.array([[1,1],[-2,1]])

In [43]:
B2

array([[ 1,  1],
       [-2,  1]])

In [44]:
B1 = np.array([[1,0],[0,1]])

In [45]:
B1

array([[1, 0],
       [0, 1]])

In [46]:
B2_inv = np.linalg.inv(B2)

In [56]:
v1 = np.array([[25],[28]])

In [57]:
v1

array([[25],
       [28]])

In [49]:
B2_inv

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [53]:
M = B2_inv @ B1

In [58]:
v2 = M @ v1

In [59]:
v2

array([[-1.],
       [26.]])

In [60]:
############

In [67]:
B1 = np.array([[1,0],[0,1]])

In [74]:
B1

array([[1, 0],
       [0, 1]])

In [68]:
B2 = np.array([[1,1],[-2,1]])

In [69]:
B2_inv = np.linalg.inv(B2)

In [73]:
B2

array([[ 1,  1],
       [-2,  1]])

In [70]:
B2_inv

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [71]:
v2 = np.array([[-3],[12]])

In [75]:
v2

array([[-3],
       [12]])

In [77]:
v1 = B2 @ v2

In [78]:
v1

array([[ 9],
       [18]])

In [79]:
###################

In [80]:
v1 = np.array([[1],[1]])

In [81]:
v1

array([[1],
       [1]])

In [82]:
B1 = np.array([[1,2],[1,1]])

In [83]:
B1

array([[1, 2],
       [1, 1]])

In [85]:
v2 = B1 @ v1

In [86]:
v2

array([[3],
       [2]])

In [87]:
###############

In [88]:
#Graded Questions

In [89]:
v1 = np.array([[3],[2]])

In [90]:
B1 = np.array([[1,0],[0,1]])

In [91]:
B2 = np.array([[3,-3],[4,-5]])

In [92]:
B2_inv = np.linalg.inv(B2)

In [93]:
B2_inv

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [94]:
M = B1 @ B2_inv

In [95]:
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [96]:
v2 = M @ v1

In [97]:
v2

array([[3.],
       [2.]])